### PR TITLE
Return warnings as validationErrors, create list of warning/suggestio…

### PR DESCRIPTION
**Pull request by ramonakira**
Create a list of warnings and suggestions, translating each individual string instead of trying to translate the joined string. This fixes non-working translations.

Thanks to @wadevries

### CODE REVIEW

**Comment by pawamoy** [comment]
What is the impact of changing the exception message type from string to list? Will it still be nicely displayed by Django once the template is rendered?

**Comment by ramonakira** [comment]
Nothing will really change as validation errors are (as always) displayed in a list, only now the feedback and warnings each get their own list-item. And (big plus for us) the translated strings that we get from zxcvbn can actually be used.

**Comment by pawamoy** [comment]
Alright then, thank you for the clarification. Merging! Thanks!

**Comment by pawamoy** [comment]
I released version 2.1.0, if something is not working please open a new issue :slightly_smiling_face:

**Pull request merged**
