### PR TITLE
Avoid using deprecated ugettext

### PR DESCRIPTION
**Pull request by nijel**
This is long deprecated and removed in Django 4.0.

### CODE REVIEW

**Comment by pawamoy** [comment]
Thanks!

**Comment by nijel** [comment]
Thanks for merging! Having this released would allow using django-zxcvbn-password
with Django 4.0.

**Comment by pawamoy** [comment]
Yes, I saved the notification, I'll try to release it soon :)

**Comment by pawamoy** [comment]
Just published v2.1.1

**Pull request merged**
