### PR TITLE
Update widgets.py

### PR DESCRIPTION
**Pull request by narcotic1998**

### CODE REVIEW

**Comment by pawamoy** [comment]
Hi, thanks for the PR? Could you explain what's it for? I think you want to have distinct classes for both password and confirmation fields?

**Comment by narcotic1998** [comment]
Yeah,as per now the code displays warning only if two fields are key up.
But if we distinct two classes of the fields it will display warnings
separately. See the screenshot below.

**Comment by narcotic1998** [comment]
I actually downloaded the code from github and then changed the name of the
classes and then installed the setup.py to implement it. Thank You.

**Comment by pawamoy** [comment]
I did not get the screenshot! Also, suddenly making the warning appear on both fields would be disruptive for people using this app. I think, if we were to merge it, it should be an option, defaulting to the original behavior.

**Pull request closed without merging**
